//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.3
//
// Created by Quasar Development at 11-04-2014
//
//---------------------------------------------------


#import "GDUsurveyAnswer.h"
#import "GDUHelper.h"
#import "GDUsurveyQuestion.h"


@implementation GDUsurveyQuestion
@synthesize answer;
@synthesize _id;
@synthesize question;

+ (GDUsurveyQuestion *)createWithXml:(DDXMLElement *)__node __request:(GDURequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(GDURequestResultHandler*) __request{
    if(self = [self init])
    {
        if([GDUHelper hasValue:__node name:@"answer"])
        {
            NSArray* __items=[__node elementsForName:@"answer"];
            for (DDXMLElement* __item in __items) {
                [self.answer addObject:(GDUsurveyAnswer*)[__request createObject:__item type:[GDUsurveyAnswer class]]];
            }
        }
        if([GDUHelper hasValue:__node name:@"id"])
        {
            self._id = [[GDUHelper getNode:__node name:@"id"] stringValue];
        }
        if([GDUHelper hasValue:__node name:@"question"])
        {
            self.question = [[GDUHelper getNode:__node name:@"question"] stringValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(GDURequestResultHandler*) __request
{

             
        if(self.answer!=nil)
        {
            for (GDUsurveyAnswer* __item in self.answer) {
                DDXMLElement* __answerItemElement=[__request writeElement:answer type:[GDUsurveyAnswer class] name:@"answer" URI:@"" parent:__parent skipNullProperty:NO];
                if(__answerItemElement!=nil)
                {
                    [__item serialize:__answerItemElement __request: __request];
                }
            }
        }
             
        DDXMLElement* ___idItemElement=[__request writeElement:_id type:[NSString class] name:@"id" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(___idItemElement!=nil)
        {
            [___idItemElement setStringValue:self._id];
        }
             
        DDXMLElement* __questionItemElement=[__request writeElement:question type:[NSString class] name:@"question" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__questionItemElement!=nil)
        {
            [__questionItemElement setStringValue:self.question];
        }


}
@end
