//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.3
//
// Created by Quasar Development at 11-04-2014
//
//---------------------------------------------------


#import "GDUsurveyQuestion.h"
#import "GDUHelper.h"
#import "GDUsurvey.h"


@implementation GDUsurvey
@synthesize _id;
@synthesize questions;

+ (GDUsurvey *)createWithXml:(DDXMLElement *)__node __request:(GDURequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(GDURequestResultHandler*) __request{
    if(self = [self init])
    {
        if([GDUHelper hasValue:__node name:@"id"])
        {
            self._id = [[GDUHelper getNode:__node name:@"id"] stringValue];
        }
        if([GDUHelper hasValue:__node name:@"questions"])
        {
            NSArray* __items=[__node elementsForName:@"questions"];
            for (DDXMLElement* __item in __items) {
                [self.questions addObject:(GDUsurveyQuestion*)[__request createObject:__item type:[GDUsurveyQuestion class]]];
            }
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(GDURequestResultHandler*) __request
{

             
        DDXMLElement* ___idItemElement=[__request writeElement:_id type:[NSString class] name:@"id" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(___idItemElement!=nil)
        {
            [___idItemElement setStringValue:self._id];
        }
             
        if(self.questions!=nil)
        {
            for (GDUsurveyQuestion* __item in self.questions) {
                DDXMLElement* __questionsItemElement=[__request writeElement:questions type:[GDUsurveyQuestion class] name:@"questions" URI:@"" parent:__parent skipNullProperty:NO];
                if(__questionsItemElement!=nil)
                {
                    [__item serialize:__questionsItemElement __request: __request];
                }
            }
        }


}
@end
