//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.3
//
// Created by Quasar Development at 11-04-2014
//
//---------------------------------------------------



#import <Foundation/Foundation.h>

#import "GDUcustomer.h"
#import "GDUgetSensorDataResponse.h"
#import "GDUsurvey.h"
#import "DDXML.h"

@class GDURequestResultHandler;



@interface GDUWSPortBinding : NSObject
    
@property (retain, nonatomic) NSDictionary* Headers;
@property (retain, nonatomic) NSString* Url;
@property (nonatomic) BOOL ShouldAddAdornments;

- (id) init;
- (id) initWithUrl: (NSString*) url;

-(NSMutableURLRequest*) creategetCustomerRequest:(NSString*) client __request:(GDURequestResultHandler*) __request;
-(GDUcustomer*) getCustomer:(NSString*) client __error:(NSError**) __error;
-(NSMutableURLRequest*) creategetSensorDataRequest:(NSString*) location __request:(GDURequestResultHandler*) __request;
-(GDUgetSensorDataResponse*) getSensorData:(NSString*) location __error:(NSError**) __error;
-(NSMutableURLRequest*) creategetUserRequestRequest:(NSString*) temperature __request:(GDURequestResultHandler*) __request;
-(NSString*) getUserRequest:(NSString*) temperature __error:(NSError**) __error;
-(GDUsurvey*) getSurvey:(NSError**) __error;
-(NSString*) getUserLocation:(NSString*) router1_mac router1_strength:(NSString*) router1_strength router2_mac:(NSString*) router2_mac router2_strength:(NSString*) router2_strength router3_mac:(NSString*) router3_mac router3_strength:(NSString*) router3_strength __error:(NSError**) __error;
-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(GDURequestResultHandler*) requestMgr; 

@end
