//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.3
//
// Created by Quasar Development at 11-04-2014
//
//---------------------------------------------------


#import "GDUWSPortBinding.h"
#import "GDURequestResultHandler.h"
#import "GDUHelper.h"

@implementation GDUWSPortBinding
@synthesize Url,ShouldAddAdornments,Headers;

- (id) init {
    if(self = [super init])
    {
        self.Url=@"REPLACE_WITH_ACTUAL_URL";
        self.ShouldAddAdornments=YES;
    }
    return self;
}

- (id) initWithUrl: (NSString*) url {
    if(self = [self init])
    {
        self.Url=url;
    }
    return self;
}

-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(GDURequestResultHandler*) requestMgr
{
    [requestMgr sendImplementation:request];
}



-(void) addAdornments:(DDXMLElement*)__methodElement
{
    if(ShouldAddAdornments)
    {
        [__methodElement addAttribute:[DDXMLNode attributeWithName:@"id" stringValue:@"o0"]];
        [__methodElement addAttribute:[DDXMLNode attributeWithName:@"c:root" stringValue:@"1"]];
    }
}

-(NSMutableURLRequest*) creategetCustomerRequest:(NSString*) client __request:(GDURequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"getCustomer" URI:@"http://myWS/" parent:__request.Body];
    [self addAdornments:__methodElement];
             
        DDXMLElement* __clientItemElement=[__request writeElement:client type:[NSString class] name:@"client" URI:@"" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__clientItemElement!=nil)
        {
            [__clientItemElement setStringValue:client];
        }
    
    NSString* __soapAction=@"";
    NSString *__soapMessage=[__request getEnvelopeString];
    NSURL *__url = [NSURL URLWithString:Url];
    NSMutableURLRequest *__requestObj = [NSMutableURLRequest requestWithURL:__url];
    NSString *msgLength = [NSString stringWithFormat:@"%d", [__soapMessage length]];

    [__requestObj addValue: @"text/xml; charset=utf-8" forHTTPHeaderField:@"Content-Type"];
    [__requestObj addValue: __soapAction forHTTPHeaderField:@"SOAPAction"];
    [__requestObj addValue: msgLength forHTTPHeaderField:@"Content-Length"];
    for (NSString* key in self.Headers) {
        [__requestObj addValue: [self.Headers objectForKey:key] forHTTPHeaderField:key];
    }
    [__requestObj setHTTPMethod:@"POST"];
    [__requestObj setHTTPBody: [__soapMessage dataUsingEncoding:NSUTF8StringEncoding]];
    return __requestObj;
}


-(GDUcustomer*) getCustomer:(NSString*) client __error:(NSError**) __error 
{
    GDURequestResultHandler* __request =[[GDURequestResultHandler alloc]init];
    NSMutableURLRequest *__requestObj=[self creategetCustomerRequest:client __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[GDUHelper getResultElement:__request.OutputBody name:@"return"];
    return (GDUcustomer*)[__request createObject:__result type:[GDUcustomer class]];
}
-(NSMutableURLRequest*) creategetSensorDataRequest:(NSString*) location __request:(GDURequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"getSensorData" URI:@"http://myWS/" parent:__request.Body];
    [self addAdornments:__methodElement];
             
        DDXMLElement* __locationItemElement=[__request writeElement:location type:[NSString class] name:@"location" URI:@"" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__locationItemElement!=nil)
        {
            [__locationItemElement setStringValue:location];
        }
    
    NSString* __soapAction=@"";
    NSString *__soapMessage=[__request getEnvelopeString];
    NSURL *__url = [NSURL URLWithString:Url];
    NSMutableURLRequest *__requestObj = [NSMutableURLRequest requestWithURL:__url];
    NSString *msgLength = [NSString stringWithFormat:@"%d", [__soapMessage length]];

    [__requestObj addValue: @"text/xml; charset=utf-8" forHTTPHeaderField:@"Content-Type"];
    [__requestObj addValue: __soapAction forHTTPHeaderField:@"SOAPAction"];
    [__requestObj addValue: msgLength forHTTPHeaderField:@"Content-Length"];
    for (NSString* key in self.Headers) {
        [__requestObj addValue: [self.Headers objectForKey:key] forHTTPHeaderField:key];
    }
    [__requestObj setHTTPMethod:@"POST"];
    [__requestObj setHTTPBody: [__soapMessage dataUsingEncoding:NSUTF8StringEncoding]];
    return __requestObj;
}


-(GDUgetSensorDataResponse*) getSensorData:(NSString*) location __error:(NSError**) __error 
{
    GDURequestResultHandler* __request =[[GDURequestResultHandler alloc]init];
    NSMutableURLRequest *__requestObj=[self creategetSensorDataRequest:location __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[GDUHelper getResultElement:__request.OutputBody name:@"getSensorDataResponse"];
    return (GDUgetSensorDataResponse*)[__request createObject:__result type:[GDUgetSensorDataResponse class]];
}
-(NSMutableURLRequest*) creategetUserRequestRequest:(NSString*) temperature __request:(GDURequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"getUserRequest" URI:@"http://myWS/" parent:__request.Body];
    [self addAdornments:__methodElement];
             
        DDXMLElement* __temperatureItemElement=[__request writeElement:temperature type:[NSString class] name:@"temperature" URI:@"" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__temperatureItemElement!=nil)
        {
            [__temperatureItemElement setStringValue:temperature];
        }
    
    NSString* __soapAction=@"";
    NSString *__soapMessage=[__request getEnvelopeString];
    NSURL *__url = [NSURL URLWithString:Url];
    NSMutableURLRequest *__requestObj = [NSMutableURLRequest requestWithURL:__url];
    NSString *msgLength = [NSString stringWithFormat:@"%d", [__soapMessage length]];

    [__requestObj addValue: @"text/xml; charset=utf-8" forHTTPHeaderField:@"Content-Type"];
    [__requestObj addValue: __soapAction forHTTPHeaderField:@"SOAPAction"];
    [__requestObj addValue: msgLength forHTTPHeaderField:@"Content-Length"];
    for (NSString* key in self.Headers) {
        [__requestObj addValue: [self.Headers objectForKey:key] forHTTPHeaderField:key];
    }
    [__requestObj setHTTPMethod:@"POST"];
    [__requestObj setHTTPBody: [__soapMessage dataUsingEncoding:NSUTF8StringEncoding]];
    return __requestObj;
}


-(NSString*) getUserRequest:(NSString*) temperature __error:(NSError**) __error 
{
    GDURequestResultHandler* __request =[[GDURequestResultHandler alloc]init];
    NSMutableURLRequest *__requestObj=[self creategetUserRequestRequest:temperature __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[GDUHelper getResultElement:__request.OutputBody name:@"return"];
    return [__result stringValue];
}


-(GDUsurvey*) getSurvey:(NSError**) __error 
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}


-(NSString*) getUserLocation:(NSString*) router1_mac router1_strength:(NSString*) router1_strength router2_mac:(NSString*) router2_mac router2_strength:(NSString*) router2_strength router3_mac:(NSString*) router3_mac router3_strength:(NSString*) router3_strength __error:(NSError**) __error 
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

@end
